project_id = "iorxmepjaqagfxnyptvb"

[functions.share-event]
verify_jwt = false

[functions.send-confirmation]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.events-feed]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.events-feed-all]
verify_jwt = false

[functions.events-feed-top4]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = true

[functions.create-comped-attendee]
verify_jwt = true

[functions.process-free-order]
verify_jwt = false

[functions.admin-list-attendees]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-order-by-session]
verify_jwt = false

[functions.create-training-payment]
verify_jwt = false

[functions.admin-list-customers]
verify_jwt = true

[functions.admin-update-person-notes]
verify_jwt = true
