// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iorxmepjaqagfxnyptvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcnhtZXBqYXFhZ2Z4bnlwdHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTc5MjcsImV4cCI6MjA3MDQzMzkyN30.DSeXkMOG6jfO4KQtbbO0dwNi-5LpLqWucMOFsReJMU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});